#include <linux/types.h>
#include <linux/device.h>


#define SUPPORTED_FIRMWARES_NUM 1


#define FAN_SPEED_CONFIG_NUM 6
#define FAN_RPM_BLOCK_NUM 2


#define BATTERY_THRESHOLD_OFFSET 0x80


#define FAN_RPM_BASE 0x74B30


#define CPU_FAN_SPEED_CONFIG_ADDR 0x72
#define GPU_FAN_SPEED_CONFIG_ADDR 0x8A
#define CPU_FAN_SPEED_ADDR 0x71
#define GPU_FAN_SPEED_ADDR 0x89
#define CPU_FAN_RPM_ADDR 0xCC
#define GPU_FAN_RPM_ADDR 0xCA
#define CPU_TEMP_ADDR 0x68
#define GPU_TEMP_ADDR 0x80 
#define PERFORMANCE_MODE_ADDR 0xF2
#define FAN_MODE_ADDR 0xF4
#define BATTERY_THRESHOLD_ADDR 0xEF
#define COOLER_BOOST_ADDR 0x98
#define BACKLIGHT_LED_LEVEL_ADDR 0xF3


#define LOW_PERFORMANCE 0xC2
#define MEDIUM_PERFORMANCE 0xC1
#define HIGH_PERFORMANCE 0xC0
#define TURBO_PERFORMANCE 0xC4
#define AUTO_PERFORMANCE 0x80


#define AUTO_FAN 0x0D
#define ADVANCED_FAN 0x8D


#define CB_OFF 0x02
#define CB_ON 0x82


#define BACKLIGHT_OFF 0x80
#define BACKLIGHT_LOW 0x81
#define BACKLIGHT_MEDIUM 0x82
#define BACKLIGHT_HIGH 0x83